name = "reglas"
main = "src/index.js"
compatibility_date = "2026-01-01"

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "reglas"
database_id = "a74b9d9a-f23d-486b-811e-c8de8f993b44"